[package]
name = "simple_bitcoin_chain"
version = "0.1.0"
edition = "2021"


[dependencies]
sha2 = "0.10.8"      # 用于计算哈希
hex = "0.4.3"        # 用于编码哈希输出为十六进制字符串
chrono = "0.4.31"     # 用于时间戳
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
